services:
  - type: web
    name: travel-planner
    runtime: docker
    plan: free
    branch: fastapi-web
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: KAKAO_REST_API_KEY
        sync: false
      - key: TMAP_OPEN_API_APP_KEY
        sync: false
      - key: TOUR_API_SERVICE_KEY
        sync: false
      - key: KEY_SERVER_TOKEN
        sync: false
